girlapp/urls.py
from django.urls import path
from . import views
from .views import (IssueCreateView, IssueDetailView,
                    IssueListView, IssueUpdateView,
                    IssueDeleteView, CommentUpdateView, CommentDeleteView,
                    UserIssueListView)

app_name = 'girlapp'

urlpatterns = [
    path('', views.index, name='girlapp-home'),
    path('home/', IssueListView.as_view(), name='girlapp-index'),
    path('user/<str:username>/', UserIssueListView.as_view(), name='user-issues'),
    # path('<int:pk>/', QuestionDetailView.as_view(), name='question-detail'),
    path('create_new/', IssueCreateView.as_view(), name='issue-create'),
    path('<int:pk>/update/', IssueUpdateView.as_view(), name='issue-update'),
   # path('<int:pk>/comment/', CommentCreateView.as_view(),
    #     name='question-comment'),
    path('<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
    # path('<int:pk>/delete_comment/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('<int:pk>/delete/', IssueDeleteView.as_view(), name='issue-delete'),
    # path('<int:pk>/comment/', Comm.as_view(), name='question-comment'),


   # path('create_new/', views.create_quiz, name='question-create'),
    path('(?P<issue_id>[0-9]+)/', views.detail, name='issue-detail'),
   # path('(?P<quiz_id>[0-9]+)/comment/', views.detail, name='question-comment'),
   # path('(?P<quiz_id>[0-9]+)/delete/', views.delete, name='question-delete'),
]

girlcue/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from usersapp import views as user_views
from django.contrib import admin
from django.conf.urls import url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('girlapp.urls')),

    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='usersapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='usersapp/logout.html'), name='logout'),

    # Password Reset
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='usersapp/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='usersapp/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='usersapp/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),


    path('update-profile/', user_views.profile_update, name='update-profile'),
    path('user_profile/', user_views.user_profile, name='user-profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

girlapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Issue(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('girlapp:issue-detail', args=[str(self.pk)])


class Comment(models.Model):
    comment = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.comment

girlapp/forms.py
from django import forms
from .models import Comment, Issue


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']


class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue
        fields = ['title', 'content']

girlapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from .models import Issue, Comment
from .forms import CommentForm, IssueForm


class IssueListView(LoginRequiredMixin, ListView):
	model = Issue
	template_name = 'girlapp/index.html'
	context_object_name = 'issues'
	ordering = ['-created']
	paginate_by = 2


class UserIssueListView(ListView):
	model = Issue
	template_name = 'girlapp/user_issues.html'
	context_object_name = 'issues'
	paginate_by = 7

	def get_queryset(self):
		user = get_object_or_404(User, username=self.kwargs.get('username'))
		return Issue.objects.filter(user=user).order_by('-created')


class IssueDetailView(DetailView):
	model = Issue


class IssueCreateView(LoginRequiredMixin, CreateView):
	model = Issue
	fields = ['title', 'content']

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)


class IssueUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Issue

	fields = ['title', 'content']

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)

	def test_func(self):
		issue = self.get_object()
		if self.request.user == issue.user:
			return True
		return False


class IssueDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Issue
	success_url = '/home'

	def test_func(self):
		issue = self.get_object()
		if self.request.user == issue.user:
			return True
		return False


def detail(request, issue_id):
	form = CommentForm(request.POST or None, request.FILES or None)
	issue = get_object_or_404(Issue, pk=issue_id)
	if form.is_valid():
		comm = form.save(commit=False)
		comm.user = request.user
		comm.issue = issue
		comm.save()
	form = CommentForm()
	return render(request, 'girlapp/issue_detail.html', {'form': form, 'issue': issue})


def delete(request, issue_id):
	issue = get_object_or_404(Issue, pk=issue_id)
	issue.delete()
	return redirect('quiz:quiz-index')


class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Comment

	fields = ['comment']

	def form_valid(self, form):
		form.instance.user = self.request.user
		return super().form_valid(form)

	def test_func(self):
		comment = self.get_object()
		if self.request.user == comment.user:
			return True
		return False


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Comment

	def test_func(self):
		comment = self.get_object()
		if self.request.user == comment.user:
			return True
		return False


def index(request):
	return render(request, 'girlapp/home.html')

girlapp/templates/girlapp/base.html
{% load static %}

<html lang="en">
<head>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'girlapp/css/main.css' %}">
    {% block title %}<title></title>{% endblock %}
</head>
<body>

<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand mr-4" href="{% url 'girlapp:girlapp-home' %}" style="font-family: 'Satisfy', cursive;">SheTalks</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'girlapp:girlapp-index' %}">Issues</a>

            </div>

                <!-- Navbar Right Side -->
                <div class="navbar-nav navbar-right">
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Search</button>
    </form>
                    {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'girlapp:issue-create' %}">New Issue</a>


            <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{ request.user.username }}
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                <a class="dropdown-item" href="{% url 'user-profile' %}">Profile</a>
                <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                </div>

            </li>
          </ul>


                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'register' %}">Sign Up</a>
                    {% endif %}
                </div>

            </div>
        </div>
    </nav>
</header>

<div class="container-fluid">
    <div class="row">
           <div class="col-md-12">
           {% if messages %}
               {% for message in messages %}
                   <div class="alert alert-{{ message.tags }}">
                   {{ message }}
                   </div>
               {% endfor %}
           {% endif %}

            {% block body %}

            {% endblock %}

        </div>


    </div>
</div>

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

girlapp/templates/girlapp/home.html
{% extends 'girlapp/base.html' %}
{% load static %}
{% block title %}<title>SheTalks</title>{% endblock %}
{% block body %}
<img src="{% static 'girlapp/images/gig.jpg' %}" class="img img-responsive"  alt="" style="width: 100%;">
{% endblock %}

girlapp/templates/girlapp/index.html
{% extends 'girlapp/base.html' %}

{% block title %}<title>SheTalks</title>{% endblock %}

{% block body %}
<div class="row">
    <div class="col-sm-2"></div>
{% if issues %}
    <div class="col-sm-8 content-section">
    {% for issue in issues %}
        <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ issue.user.profile.image.url }}" alt="">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'girlapp:user-issues' issue.user.username %}">{{ issue.user }}</a>
              <small class="text-muted">{{ issue.created|date:"F d, Y" }}</small>
            </div>
            <h5><a class="article-title" href="{% url 'girlapp:issue-detail' issue.id %}"> {{ issue.title }}</a></h5>
          </div>
        </article>

    {% endfor %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="{{ page_obj.previous_page_number }}">Prev</a>
            {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="{{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
        {% endif %}

    {% else %}
 <div class="alert alert-info"><h4 class="text text-center">No Issues:</h4></div>
{% endif %}
</div>
</div>


{% endblock %}

girlapp/templates/girlapp/issue_detail.html
{% extends 'girlapp/base.html' %}
{% load crispy_forms_tags %}
{% block title %}<title>SheTalks</title>{% endblock %}

{% block body %}
    <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
        <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ issue.user.profile.image.url }}" alt="">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'girlapp:user-issues' issue.user.username %}">{{ issue.user }}</a>
              <small class="text-muted">{{ issue.created|date:"F d, Y" }}</small>
                {% if issue.user == user %}
                    <div class="">
                    <a class="btn btn-secondary btn-sn mt-1 mb-1" href="{% url 'girlapp:issue-update' pk=issue.pk %}">Update</a>
                    <a class="btn btn-danger btn-sn mt-1 mb-1" href="{% url 'girlapp:issue-delete' issue.id %}">Delete</a>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ issue.title }}</h2>
            <p class="article-content">{{ issue.content }}</p>


          {% if issue.comment_set %}
              <div class="article-metadata">
              <h5 class="text-secondary text-outline-info">Comments: {{ issue.comment_set.count }}</h5>
          </div>
              {% for i in issue.comment_set.all %}
                  <p>{{ i.comment }} - <a class="mr-2" href="">{{ i.user }}</a></p>

                  {% if issue.user == user %}
                    <div class="">
                    <a class="btn btn-secondary btn-sn mt-1 mb-1" href="{% url 'girlapp:comment-update' issue.id %}">Update</a>
                    <a class="btn btn-danger btn-sn mt-1 mb-1" href="">Delete</a>
                    </div>
                {% endif %}

              {% endfor %}
              <hr>
          {% endif %}


          <br><br>
    <form method="POST" action="{% url 'girlapp:issue-detail' issue.id %}" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4"><b>Your Comment</b></legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-info">Submit</button>
    </div>
</form>
          </div>


        </article>
    </div>
    </div>

{% endblock %}

girlapp/templates/girlapp/issue_form.html
{% extends 'girlapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>New Issue</title>{% endblock %}

{% block body %}
    <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
<div class="content-section">
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4 text-primary">Share</legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-info">Submit</button>
        <button type="reset" class="btn btn-outline-danger">Cancel</button>
    </div>
</form>

</div>
    </div>
    </div>
{% endblock %}

girlapp/templates/girlapp/user_issues.html
{% extends 'girlapp/base.html' %}

{% block title %}<title>SheTalks</title>{% endblock %}

{% block body %}
    <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
{% if issues %}
    {% for issue in issues %}
        <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ issue.user.profile.image.url }}" alt="">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'girlapp:user-issues' issue.user.username %}">{{ issue.user }}</a>
              <small class="text-muted">{{ issue.created|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'girlapp:issue-detail' issue.id %}">{{ issue.title }}</a></h2>
            <p class="article-content">{{ issue.content }}</p>
          </div>
        </article>

    {% endfor %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="{{ page_obj.previous_page_number }}">Prev</a>
            {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="{{ page_obj.paginator.num_pages }}">Last</a>
            {% endif %}
        {% endif %}

{% endif %}
    </div>
    </div>
{% endblock %}