girlapp/urls.py
from django.urls import path
from . import views
from .views import (IssueCreateView, IssueDetailView,
                    IssueListView, IssueUpdateView,
                    IssueDeleteView, CommentUpdateView, CommentDeleteView,
                    UserIssueListView)

app_name = 'girlapp'

urlpatterns = [
    path('', views.index, name='girlapp-home'),
    path('home/', IssueListView.as_view(), name='girlapp-index'),
    path('user/<str:username>/', UserIssueListView.as_view(), name='user-issues'),
    # path('<int:pk>/', QuestionDetailView.as_view(), name='question-detail'),
    path('create_new/', IssueCreateView.as_view(), name='issue-create'),
    path('<int:pk>/update/', IssueUpdateView.as_view(), name='issue-update'),
   # path('<int:pk>/comment/', CommentCreateView.as_view(),
    #     name='question-comment'),
    path('<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
    # path('<int:pk>/delete_comment/<int:pk>/', CommentDeleteView.as_view(), name='comment-delete'),
    path('<int:pk>/delete/', IssueDeleteView.as_view(), name='issue-delete'),
    # path('<int:pk>/comment/', Comm.as_view(), name='question-comment'),


   # path('create_new/', views.create_quiz, name='question-create'),
    path('(?P<issue_id>[0-9]+)/', views.detail, name='issue-detail'),
   # path('(?P<quiz_id>[0-9]+)/comment/', views.detail, name='question-comment'),
   # path('(?P<quiz_id>[0-9]+)/delete/', views.delete, name='question-delete'),
]

girlcue/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from usersapp import views as user_views
from django.contrib import admin
from django.conf.urls import url


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include('girlapp.urls')),

    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='usersapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='usersapp/logout.html'), name='logout'),

    # Password Reset
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='usersapp/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='usersapp/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='usersapp/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),


    path('update-profile/', user_views.profile_update, name='update-profile'),
    path('user_profile/', user_views.user_profile, name='user-profile'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usersapp/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    bio = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, force_insert=False, force_update=False, using=None, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

usersapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {'username': None}


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['image', 'bio']

usersapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.db.models import Q
from .models import Profile
from girlapp.models import Issue


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account Created for {username}!')
            return redirect('girlapp:girlapp-index')

    else:
        form = UserRegisterForm()
    return render(request, 'usersapp/register.html', {'form': form})


@login_required
def profile_update(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your Account Has Been Updated!')
            return redirect('user-profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'usersapp/profile_update.html', context)


@login_required
def user_profile(request):

    prof = Profile.objects.get(user=request.user)
    issues = Issue.objects.filter(user=request.user)
    return render(request, 'usersapp/user_profile.html', {'prof': prof, 'issues': issues})

usersapp/templates/usersapp/login.html
{% extends 'girlapp/base.html' %}

{% block body %}
    <div class="container-fluid">
    <div class="row">
        <div class="col-md-3">

        </div>
        <div class="col-md-5" style="padding-top: 5%;">
            {% if message %}
                <div class="alert alert-danger">
                <strong>{{ message }}</strong>
                </div>
            {% endif %}
            <div class="card">
                <div class="card-header">
                    <h3 class="text-primary">Login</h3>
                </div>

                <div class="card-body">
                    <form class="form-horizontal" action="" method="post" style="margin: 15px;">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label">Username:</label>
                            <input type="text" class="form-control" name="username" >
                        </div>

                        <div class="form-group">
                            <label class="control-label">Password:</label>
                            <input type="password" class="form-control" name="password" >
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Login</button>
                        </div>
                        <div>
                            <p> Not Registered? <a href="{% url 'register' %}">Register</a></p>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
    </div>
{% endblock %}

usersapp/templates/usersapp/logout.html
{% extends 'girlapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>Logged out</title>{% endblock %}

{% block body %}
    <center>
<div class="container">
<div class="col-md-6">
<div class="content-section">
<h2>You've Logged out!</h2>
<div class="border-top pt-3">
    <small class="text-muted">Login Again: <a class="ml-2" href="{% url 'login' %}">Login</a></small>
</div>
</div>
</div>
</div>
    </center>
{% endblock %}

usersapp/templates/usersapp/profile_update.html
{% extends 'girlapp/base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<div class="row">
<div class="col-sm-4">

</div>
<div class="col-sm-4">
<div class="content-section">
  <!-- FORM HERE -->

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom text-primary">Update Profile</legend>
        {{ u_form|crispy }}
        {{ p_form|crispy }}
    </fieldset>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-info">Update</button>
    </div>
</form>

</div>
    </div>
    </div>
{% endblock %}

usersapp/templates/usersapp/register.html
{% extends 'girlapp/base.html' %}
{% load crispy_forms_tags %}
{% block  body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3">

        </div>
        <div class="col-sm-5" style="padding-top: 5%;">
            <div class="card">
                <div class="card-header">
                    <h3 class="text-primary">Sign Up</h3>
                </div>
                <div class="card-body">
                    <form method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                        <div>
                            <p>Already Registered? <a href="{% url 'login' %}">Login</a> </p>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}

usersapp/templates/usersapp/user_profile.html
{% extends 'girlapp/base.html' %}
{% load crispy_forms_tags %}

{% block title %}<title>{{ user.username }}</title>{% endblock %}

{% block body %}
<div class="row">
<div class="col-sm-3">
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}" alt="">
    <div class="media-body">
      <h3 class="account-heading">{{ user.username }}</h3>
      <p class="text-secondary">{{ user.email }}</p>
      <p class="text-secondary">{{ user.profile.bio }}</p>
    </div>
  </div>

        <a href="{% url 'update-profile' %}" class="btn btn-outline-info">Update</a>


</div>
    </div>

<div class="col-sm-9">
{% if issues %}
    {% for issue in issues %}
        <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ issue.user.profile.image.url }}" alt="">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'girlapp:user-issues' issue.user.username %}">{{ issue.user }}</a>
              <small class="text-muted">{{ issue.created|date:"F d, Y" }}</small>
            </div>
            <h5><a class="article-title" href="{% url 'girlapp:issue-detail' issue.id %}"> {{ issue.title }}</a></h5>
          </div>
        </article>

    {% endfor %}
{% endif %}
</div>
</div>
{% endblock %}